import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-900 text-white">
          <nav className="container mx-auto flex items-center justify-between p-4">
            <div className="text-2xl font-bold">Mini Clickup</div>
            <div className="space-x-4">
              <Link href="/tasks" className="hover:border hover:border-blue-600 p-2 rounded-full">Tasks</Link>
              <Link href="/board" className="hover:border hover:border-blue-600 p-2 rounded-full">Board</Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
